FROM node:16.14.2-alpine3.15

WORKDIR /app

COPY ./package.json ./ && COPY ./yarn.lock ./

RUN apk update && apk upgrade && apk add bash

RUN yarn global add next

RUN yarn install

RUN mkdir node_modules/.cache && chmod -R 777 node_modules/.cache

COPY . .

EXPOSE 3000

CMD ["yarn", "dev"]
